### ISSUE TITLE
Write VRP instances

### ISSUE THREAD

**Issue by leonlan** [leonlan/VRPLIB#14]
It would be nice to have a function that could also write VRP instances. [This](https://github.com/ortec/euro-neurips-vrp-2022-quickstart/blob/main/tools.py) was provided in the EURO-NeurIPS competition.

**Comment by leonlan** [comment]
I made a start for writing instances. 
- [ ] Find the original VRPLIB reference
- [ ] Check for inconsistencies across the VRPLIB instances
- [ ] Think about the interface: how do we infer from `instance` which attributes should be written?

**Comment by leonlan** [comment]
See http://www.bernabe.dorronsoro.es/vrp/index.html?/Problem_Instances/VRPLIBDesc.html for the original VRPLIB descrption.

**Comment by leonlan** [comment]
webhotel4.ruc.dk/~keld/research/LKH-3/ 

LKH-3 VRPLIB convention

**Comment by leonlan** [comment]
The [VRPLIB](http://www.bernabe.dorronsoro.es/vrp/index.html?/Problem_Instances/VRPLIBDesc.html) format consists of a problem specification part and a data part. 

- The problem specification indicates the type of the problem. This includes the name, comments, problem type, dimensions, edge weight type, and problem-specific scalar information (e.g., capacity, duration limit, ...).
- The data consists of _sections_, e.g., coordinates, demands, time windows, etc. For most vehicle routing problems, these are node-related attributes. Each section starts with the section name (e.g., `DEMAND_SECTION`), then $n$ rows of the corresponding data.

**Comment by leonlan** [comment]
Both for reading and writing files, we should follow the LKH-3 VRPLIB format.

But the Solomon and GH instances do not follow the VRPLIB format. What do I want to do with that?

**Comment by leonlan** [comment]
https://www.sintef.no/projectweb/top/vrptw/100-customers/

LKH-3 calls this "Sintef solution style"

**Comment by leonlan** [comment]
I have removed the `write` module because this wasn't ready yet, and I want to speed up the release of V1. So this is an open issue again.

**Comment by leonlan** [comment]
https://github.com/leonlan/VRPLIB/commit/885f9cce19bb5440a6c4c1ee899754d3b0c42728#diff-6fa8cb67482a47a8390d40bcd32b10d53f6ffd7a723f412d71a486039267557f

**Comment by N-Wouda** [comment]
This is periodically useful for the PyVRP instances as well (I'm running into this now with multi-depot VRP). Do you want to be really strict about what's written? A simple dict -> specification/section type writer is easy enough: every value that's iterable becomes a section, and every value that's not becomes a specification. The onus would then be on the user to ensure that data encodes a valid VRPLIB instances, but to be fair, that's on the user anyway when they're writing instances.

**Comment by leonlan** [comment]
Yeah that seems like a good solution to me. I'll try to make this feature later this week.

**Comment by leonlan** [comment]
@N-Wouda I implemented the `write_instance` and `write_solution` functions. Hopefully, they are useful!
